# Generated by Django 2.1.2 on 2018-10-17 03:31

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedFax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', jsonfield.fields.JSONField()),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
    ]
