# Generated by Django 2.1.2 on 2018-10-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedfax',
            name='media_url',
            field=models.TextField(default=''),
        ),
    ]
