# Generated by Django 2.1.2 on 2018-10-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_receivedfax_media_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivedfax',
            name='payload',
        ),
        migrations.AddField(
            model_name='receivedfax',
            name='num_pages',
            field=models.IntegerField(default=1),
        ),
    ]
